#
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
      
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub" # See documentation for possible values.
    directory: "" # Location of package manifests
    schedule:
      interval: "daily"
      
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"      

updates:
  - package-ecosystem: "npm"
    directory: ""
    schedule:
      interval: "daily"
    # Update the npm manifest file to relax
    # the version requirements
    versioning-strategy: widen

  - package-ecosystem: "composer"
    directory: ""
    schedule:
      interval: "daily"
    # Increase the version requirements for Composer
    # only when required
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "pip"
    directory: ""
    schedule:
      interval: "daily"
    # Only allow updates to the lockfile for pip and
    # ignore any version updates that affect the manifest
    versioning-strategy: lockfile-only

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /sala/assets/plugins/PHPExcel-1.8/Documentation/assets/ClassDiagrams
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/consulta/estadisticas/notascorte/data
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/consulta/estadisticas/notascorte/jquery/development-bundle
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/consulta/estadisticas/riesgos/data
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/consulta/estadisticas/riesgos/jquery/development-bundle
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/convenio/DataTables
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/convenio/jQueryFileUpload
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/convenio/jQueryFileUpload/server/node
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/js/jquery-ui-1.10.4.custom/development-bundle
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/men/DataTables-1.9.4
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/observatorio/data
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /serviciosacademicos/observatorio/data2
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /serviciosacademicos/mgi/tablero_siq/Highcharts-2.3.3/exporting-server/java/highcharts-export
    schedule:
      interval: daily
