name: Secure Development Workflow

on: [push]

jobs:
  combined:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Vulnerability scan
        uses: debricked/actions@2484ae836362432478822815b28311aa8cd25954 # v3.3.0
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
      - name: Resolve vulnerabilities
        if: always()  # Always attempt resolution, even after failures
        uses: debricked/actions/resolve@2484ae836362432478822815b28311aa8cd25954 # v3.3.0
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
          # Add optional inputs for vulnerability prioritization and resolution strategies
          # e.g., DEBRICKED_RESOLVE_STRATEGY: upgrade, DEBRICKED_SEVERITY_THRESHOLD: high
          # See https://debricked.com/docs/actions/resolve for complete list
