name: Secure Development Workflow

on: [push]

jobs:
  combined:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Vulnerability scan
        uses: debricked/actions@659ae7accc12313772fbfbd1b1fccec31772ce41 # v4.0.0
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
      - name: Resolve vulnerabilities
        if: always()  # Always attempt resolution, even after failures
        uses: debricked/actions/resolve@659ae7accc12313772fbfbd1b1fccec31772ce41 # v4.0.0
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
          # Add optional inputs for vulnerability prioritization and resolution strategies
          # e.g., DEBRICKED_RESOLVE_STRATEGY: upgrade, DEBRICKED_SEVERITY_THRESHOLD: high
          # See https://debricked.com/docs/actions/resolve for complete list
