name: Psalm – Security Scanner for PHP
uses: psalm/psalm-github-security-scan@1.2.1


on: [push, pull_request]

permissions:
  contents: read

jobs:
  psalm:
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Psalm Security Scan
        uses: docker://ghcr.io/psalm/psalm-security-scan:latest@sha256:27d57b9f5c154caa456b3cd124bb1d49096c1ce3794dc6eb579ec304058a03f6
        
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@23acc5c183826b7a8a97bce3cecc52db901f8251 # v3.25.10
        with:
          sarif_file: results.sarif
